apiVersion: exposedeploy.example.com/v1alpha1
kind: ExposeDeployment
metadata:
  name: first-exposedeployment-object
spec:
  replicas: 1
  image: busybox:latest
  minavailabletimesec: 10
  customenv:
    - "echo hello"

  portdefinition:
    port: 80
    targetport: 80