---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-exposedeploy-example-com-v1alpha1-exposedeployment
  failurePolicy: Fail
  name: mexposedeployment-v1alpha1.kb.io
  rules:
  - apiGroups:
    - exposedeploy.example.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - exposedeployments
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-exposedeploy-example-com-v1alpha1-exposedeployment
  failurePolicy: Fail
  name: vexposedeployment-v1alpha1.kb.io
  rules:
  - apiGroups:
    - exposedeploy.example.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - exposedeployments
  sideEffects: None
