//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomCondition) DeepCopyInto(out *CustomCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomCondition.
func (in *CustomCondition) DeepCopy() *CustomCondition {
	if in == nil {
		return nil
	}
	out := new(CustomCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExposeDeployment) DeepCopyInto(out *ExposeDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExposeDeployment.
func (in *ExposeDeployment) DeepCopy() *ExposeDeployment {
	if in == nil {
		return nil
	}
	out := new(ExposeDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExposeDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExposeDeploymentList) DeepCopyInto(out *ExposeDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ExposeDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExposeDeploymentList.
func (in *ExposeDeploymentList) DeepCopy() *ExposeDeploymentList {
	if in == nil {
		return nil
	}
	out := new(ExposeDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExposeDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExposeDeploymentSpec) DeepCopyInto(out *ExposeDeploymentSpec) {
	*out = *in
	if in.CustomEnv != nil {
		in, out := &in.CustomEnv, &out.CustomEnv
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.PortDefinition = in.PortDefinition
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExposeDeploymentSpec.
func (in *ExposeDeploymentSpec) DeepCopy() *ExposeDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(ExposeDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExposeDeploymentStatus) DeepCopyInto(out *ExposeDeploymentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]CustomCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExposeDeploymentStatus.
func (in *ExposeDeploymentStatus) DeepCopy() *ExposeDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(ExposeDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortDefinition) DeepCopyInto(out *PortDefinition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortDefinition.
func (in *PortDefinition) DeepCopy() *PortDefinition {
	if in == nil {
		return nil
	}
	out := new(PortDefinition)
	in.DeepCopyInto(out)
	return out
}
